<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <RootNamespace>VB.Specs</RootNamespace>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.11.2" />
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" Version="2.4.1" />
    <PackageReference Include="xunit.v3" Version="4.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Src\AwesomeAssertions\AwesomeAssertions.csproj" />
  </ItemGroup>

</Project>
