<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net472;net8.0;net10.0</TargetFrameworks>
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>..\..\Src\AwesomeAssertions.snk</AssemblyOriginatorKeyFile>
    <IsPackable>false</IsPackable>
    <DebugType>full</DebugType>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net472'">
    <PackageReference Include="System.Collections.Immutable" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" Version="2026.2.0" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.11.2" />
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" Version="2.4.1" />
    <PackageReference Include="xunit.v3" Version="4.0.1" />
    <PackageReference Include="Xunit.StaFact" Version="4.0.23" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Src\AwesomeAssertions\AwesomeAssertions.csproj" />
    <ProjectReference Include="..\AssemblyA\AssemblyA.csproj" />
    <ProjectReference Include="..\AssemblyB\AssemblyB.csproj" />
    <ProjectReference Include="..\ExampleExtensions\ExampleExtensions.csproj" />
  </ItemGroup>

</Project>
