<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <RootNamespace>MSTestV4.Mtp.Specs</RootNamespace>
    <AssemblyName>MSTestV4.Mtp.Specs</AssemblyName>
    <OutputType>Exe</OutputType>

    <!-- from https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-mstest-running-tests -->
    <!-- Enable Microsoft.Testing.Platform, this is an opt-in feature -->
    <EnableMSTestRunner>true</EnableMSTestRunner>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Src\AwesomeAssertions\AwesomeAssertions.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.11.2" />
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" Version="2.4.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.4.1" />
    <PackageReference Include="MSTest.TestFramework" Version="4.4.1" />
  </ItemGroup>
</Project>
